name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install directories
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Install Terser
        run: npm install --save-dev terser

      - name: Fix Rollup Dependencies
        run: |
          cd node_modules/rollup
          npm install --no-save @rollup/rollup-linux-x64-gnu

      - name: Build
        run: npm run build

      - name: Ensure CNAME and config files are copied
        run: |
          # Copy CNAME file
          if [ -f "CNAME" ]; then
            cp CNAME dist/
          fi
          if [ -f "public/CNAME" ]; then
            cp public/CNAME dist/
          fi
          # Force create CNAME file if it doesn't exist
          echo "connergroth.me" > dist/CNAME

          # Create GitHub Pages config
          echo '{ "dependencies": {}, "scripts": {} }' > dist/package.json

          # Create .gitattributes for MIME types
          cat > dist/.gitattributes << EOF
*.js    linguist-language=JavaScript
*.mjs   linguist-language=JavaScript
*.css   linguist-language=CSS
*.json  linguist-language=JSON
*.svg   linguist-language=SVG
EOF

          # Create .nojekyll file
          touch dist/.nojekyll

          # Create specific MIME type file for GitHub Pages
          mkdir -p dist/.well-known
          cat > dist/.well-known/mimetypes << EOF
application/javascript  .js
application/javascript  .mjs
text/css                .css
application/json        .json
image/svg+xml           .svg
EOF

          # Ensure index.html exists
          if [ ! -f "dist/index.html" ]; then
            echo "WARNING: No index.html found in dist directory!"
          fi

      - name: Verify dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Checking for CNAME file:"
          cat dist/CNAME || echo "CNAME file not found!"
          echo "Checking if index.html exists:"
          test -f dist/index.html && echo "index.html exists" || echo "WARNING: index.html not found!"
          echo "Checking MIME type configuration:"
          ls -la dist/.well-known/ || echo "MIME type configuration not found!"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy
          branch: gh-pages # The branch to deploy to
          clean: true # Automatically remove deleted files from the deploy branch
