name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install directories
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Install Terser
        run: npm install --save-dev terser

      - name: Fix Rollup Dependencies
        run: |
          cd node_modules/rollup
          npm install --no-save @rollup/rollup-linux-x64-gnu

      - name: Build
        run: npm run build

      - name: Ensure CNAME and config files are copied
        run: |
          # Copy CNAME file
          if [ -f "CNAME" ]; then
            cp CNAME dist/
          fi
          if [ -f "public/CNAME" ]; then
            cp public/CNAME dist/
          fi
          # Force create CNAME file if it doesn't exist
          echo "connergroth.me" > dist/CNAME

          # Copy _headers file if it exists
          if [ -f "_headers" ]; then
            cp _headers dist/
          fi
          if [ -f "public/_headers" ]; then
            cp public/_headers dist/
          fi

          # Create .nojekyll file
          touch dist/.nojekyll

          # Ensure index.html exists
          if [ ! -f "dist/index.html" ]; then
            echo "WARNING: No index.html found in dist directory!"
          fi

      - name: Verify dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Checking for CNAME file:"
          cat dist/CNAME || echo "CNAME file not found!"
          echo "Checking if index.html exists:"
          test -f dist/index.html && echo "index.html exists" || echo "WARNING: index.html not found!"
          echo "Checking for _headers file:"
          test -f dist/_headers && echo "_headers exists" || echo "WARNING: _headers not found!"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy
          branch: gh-pages # The branch to deploy to
          clean: true # Automatically remove deleted files from the deploy branch
